# --- Constants and Configuration ---
RPPG_MODEL_FILE_NAME = "pose_landmarker.task"
CAMERA_ID = 2
STANDARD_SIZE_OF_FOR_OPTICAL_FLOW = (640, 480)

# Parameter default untuk kamera jika tidak terdeteksi
DEFAULT_CAM_WIDTH = 640
DEFAULT_CAM_HEIGHT = 480
DEFAULT_CAM_FPS = 30

# Parameter rPPG
RPPG_RGB_BUFFER_SECONDS = 15
RPPG_POS_DISPLAY_SECONDS = 10
RPPG_POS_LOWCUT_HZ = 0.75
RPPG_POS_HIGHCUT_HZ = 3.0 # Sesuai dengan 45-180 BPM
RPPG_POS_FILTER_ORDER = 3
RPPG_MIN_HR_BPM = 35
RPPG_MAX_HR_BPM = 180
RPPG_PEAK_PROMINENCE = 0.4 # Untuk deteksi puncak sinyal POS ternormalisasi

# Parameter Respirasi (Optical Flow)
RESP_OF_RAW_BUFFER_SECONDS = 20
RESP_OF_FILTERED_DISPLAY_SECONDS = 10 # Sama dengan POS display buffer
RESP_OF_LK_WIN_SIZE = (15,15)
RESP_OF_LK_MAX_LEVEL = 2
RESP_OF_LK_CRITERIA_EPS = 0.03
RESP_OF_LK_CRITERIA_COUNT = 10
RESP_OF_MAX_CORNERS_PER_SHOULDER = 25
RESP_OF_QUALITY_LEVEL = 0.2
RESP_OF_MIN_DISTANCE_FEATURES = 3
RESP_OF_BLOCK_SIZE_FEATURES = 3
RESP_OF_MIN_FEATURES_FOR_SIGNAL = 5 # Minimal fitur yang harus terlacak
RESP_OF_LOWCUT_HZ = 0.1  # 6 RPM
RESP_OF_HIGHCUT_HZ = 0.5 # 30 RPM
RESP_OF_FILTER_ORDER = 2
RESP_OF_MEDIAN_FILTER_WINDOW_SECONDS = 0.5 # Untuk menghilangkan spike noise
RESP_OF_PEAK_PROMINENCE_FACTOR = 0.6 # Faktor untuk adaptive prominence
RESP_OF_MIN_PEAK_PROMINENCE = 0.35
RESP_OF_PEAK_WIDTH_MIN_SECONDS = 0.1
RESP_OF_PEAK_WIDTH_MAX_SECONDS = 2.0
RESP_OF_RPM_MOVING_AVG_INTERVALS = 3 # Jumlah interval antar puncak untuk moving average RPM
RESP_MIN_RPM = 6
RESP_MAX_RPM = 25

# Parameter ROI Bahu untuk Optical Flow
SHOULDER_ROI_WIDTH = 60
SHOULDER_ROI_HEIGHT = 40

# Parameter ROI Dahi untuk rPPG (proporsi dari bounding box wajah)
FOREHEAD_ROI_Y_START_FACTOR = 0.10
FOREHEAD_ROI_Y_END_FACTOR = 0.25
FOREHEAD_ROI_X_START_FACTOR = 0.20
FOREHEAD_ROI_X_END_FACTOR = 0.80

# Parameter Tampilan
DISPLAY_GRAPH_HEIGHT = 120
DISPLAY_PANEL_PADDING = 10
DISPLAY_GRAPH_TITLE_SPACE = 20
DISPLAY_GRAPH_TEXT_COLOR = (0,0,0)
DISPLAY_GRID_COLOR = (220,220,220)
DISPLAY_CAMERA_PORTION_W_FACTOR = 0.35 # Persentase lebar total untuk kamera
DISPLAY_MIN_TOTAL_WIDTH = 1280
DISPLAY_MIN_GRAPH_WIDTH = 100
DISPLAY_LAYOUT_INFO_AREA_HEIGHT = 40 # Area tambahan untuk info di bawah grafik
DISPLAY_BACKGROUND_COLOR = (220,220,220)
OUTPUT_VIDEO_FILENAME = "output_rppg_respiration_resized_layout.mp4"
FINAL_RPPG_PLOT_FILENAME = "final_rppg_plot_webcam.png"
FINAL_RESPIRATION_PLOT_FILENAME = "final_respiration_shoulder_movement_plot.png"
